# Generated by Django 4.1.2 on 2022-11-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='giachoib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenlp', models.CharField(max_length=700)),
                ('lpgh', models.CharField(max_length=600)),
                ('cglp', models.CharField(max_length=500)),
            ],
        ),
    ]
